package sml;

import java.util.Objects;

/**
 * <p>Used as an indicator for other instructions to "jump" to a particular label.</p>
 * The label name is wrapped within the Label record class, ensuring type safety.
 * This provides better code readability and ensures related errors can be caught at compile time.
 * @param label label, a sequence of non-whitespace characters
 */
public record Label(String label) {

    public Label {
        Objects.requireNonNull(label);
    }

    @Override
    public String toString() {
        return label;
    }

    // .equals and .hashCode are generated by the Java compiler within a record class.
    // Thus, they do not need to be overridden here.
}
